### ISSUE TITLE
travis error on php 5.4

### ISSUE THREAD

**Issue by samsonasik** [gianarb/penny-classic-app#28]
this : https://travis-ci.org/pennyphp/penny-classic-app/jobs/82943626
it may be because of we use `zendframework/zend-eventmanager:~2.4` which led to `>=2.4,<3.0` . If we want to keep using php 5.4, we need to use lts version instead ( aka `zendframework/zend-eventmanager:~2.4.0` )

Thought ?

**Comment by samsonasik** [comment]
another alternative, is,we upgrade to php 5.5

**Comment by gianarb** [comment]
yes.. I have the same idea :)

**Comment by samsonasik** [comment]
@gianarb please re-start travis build now ;)

**Comment by gianarb** [comment]
Green! Thanks!
