### ISSUE TITLE
make release same as penny

### ISSUE THREAD

**Issue by samsonasik** [gianarb/penny-classic-app#31]
I think we can have a release for clasic-app with same as penny, after each release. For example: we just released penny 0.5, so we can have penny-clasic-app with release 0.5, and upper requirement of penny in composer.json with the version updated, thoughts?

**Comment by gianarb** [comment]
Hello! 
In my opinion this is not a good idea, this project should helps developers during startup your new project.. It supports the last stable status and stop :)

**Comment by samsonasik** [comment]
Ok, but dev-master may still more buggy before release, how about using penny:0.\* instead of penny:dev-master ?

Warm regards,

Abdul Malik Ikhsan

Pada 3 Okt 2015, pukul 16.00, Gianluca Arbezzano notifications@github.com menulis:

**Comment by samsonasik** [comment]
#32 is what I mean ;)
