### ISSUE TITLE
Demo applications

### ISSUE THREAD

**Issue by fntlnz** [gianarb/penny-classic-app#33]
Today I wrote a small demo application that uses twig instead of plates, the symfony request/response instead of the diactoros ones, doctrine/orm and since I needed a way to build forms I used the symfony/form component.

I was wondering if it's worth to have a repository of demo applications like this one to show potential users how penny is easy to integrate with existing components and how can be surprisingly simple creating applications with it.

What do you think?

Oh, and you can find the demo application here: https://github.com/fntlnz/penny-classic-app/tree/bookshelf

**Comment by fntlnz** [comment]
@gianarb  In reply to this: https://github.com/pennyphp/penny-classic-app/issues/34#issuecomment-147310682

> IMO we can move this implementation (symfony like) in another repo if you agree..

I was thinking on something like a repository where the master is empty  with just a README with links to other branches and each branch contains an implementation of a demo application.

Could be ok for you?

**Comment by gianarb** [comment]
Perfect! :)
