### ISSUE TITLE
Controller Exception event listener

### ISSUE THREAD

**Issue by fntlnz** [gianarb/penny-classic-app#34]
At the state of art when an exception is raised during a controller execution it is been catched and and event is triggered (https://github.com/pennyphp/penny/blob/master/src/App.php#L123).

So for example if an Exception is raised in the `indexAction` of the `IndexController` an event named `indexcontroller.index_error` is emitted.

The penny classic app tries to attach to this kind of events here: https://github.com/pennyphp/penny-classic-app/blob/master/config/di.php#L5 but AFAIK this kind of notation `*_error` does not work.

In the Bookshelf demo application I solved it attaching to the wildcard and checking for error events at Listener  level.

https://github.com/fntlnz/penny-classic-app/blob/bookshelf/config/di.php#L5
https://github.com/fntlnz/penny-classic-app/blob/bookshelf/app/EventListener/ExceptionListener.php#L18
## In brief
- Controller level error now are giving a Blank page because exception are catched but there's no listener to handle them
- I found a solution but I'm not sure is the best one

So, any suggestions? What do you think?

**Comment by gianarb** [comment]
Thanks for your implementation, it is awesome!! :smile: 
 yes this flow in penny is very strong to understand but at the moment I have not other idea :) 

Can you apply your fix into the master?

IMO we can move this implementation (symfony like) in another repo if you agree..
