### ISSUE TITLE
https://pennyphp.org/ site is not working, but http://pennyphp.org/ does

### ISSUE THREAD

**Issue by userlond** [gianarb/penny-classic-app#39]
Hi, it's not related to code, but to official site. https://pennyphp.org is not loaded for me, but http://pennyphp.org does.

Please, replace site definition on https://github.com/pennyphp/penny-classic-app

**Comment by samsonasik** [comment]
the site is working on my site, did you try different connection? Also, the site  issue should be reported to https://github.com/pennyphp/pennyphp.github.com ;)

Warm regards,

Abdul Malik Ikhsan

Pada 1 Nov 2015, pukul 11.00, userlond notifications@github.com menulis:
