### ISSUE TITLE
register gianarb/penny-classic-app to packagist

### ISSUE THREAD

**Issue by samsonasik** [gianarb/penny-classic-app#6]
so we can install via composer create project command.

**Comment by gianarb** [comment]
Done! Thanks

**Comment by samsonasik** [comment]
where is it? i can't find it https://packagist.org/packages/gianarb/

**Comment by gianarb** [comment]
https://packagist.org/packages/penny/classic-app I'm :construction_worker:

**Comment by samsonasik** [comment]
oh yeah, thanks ;)
